#line 1 "web_schema.tmpl"
#include "content.h" 
#line 2 "web_schema.tmpl"
namespace my_skin {
	#line 3 "web_schema.tmpl"
	struct  message :public cppcms::base_view
	#line 3 "web_schema.tmpl"
	{
	#line 3 "web_schema.tmpl"
		content::message &content;
	#line 3 "web_schema.tmpl"
		message(std::ostream &_s,content::message &_content): cppcms::base_view(_s),content(_content),_domain_id(0)
	#line 3 "web_schema.tmpl"
		{
	#line 3 "web_schema.tmpl"
			_domain_id=booster::locale::ios_info::get(_s).domain_id();
	#line 3 "web_schema.tmpl"
		}
		#line 4 "web_schema.tmpl"
		virtual void render() {
		#line 4 "web_schema.tmpl"
			cppcms::translation_domain_scope _trs(out(),_domain_id);

			#line 134 "web_schema.tmpl"
			out()<<"\n"
				"<html>\n"
				"\n"
				"<head>\n"
				"\n"
				"  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\" integrity=\"sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS\" crossorigin=\"anonymous\" />\n"
				"  <link rel=\"stylesheet\" type=\"text/css\" href=\"/content/style/web_MVP.css\" />\n"
				"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n"
				"  <script src=\"https://www.gstatic.com/jsaction/contract.js\"></script>\n"
				"  <script src=\"https://www.gstatic.com/jsaction/dispatcher.js\"></script>\n"
				"  <title>Dispatching System</title>\n"
				"\n"
				"</head>\n"
				"\n"
				"<body>\n"
				"  <!--<div class=\"container-fluid\">\n"
				"    <div class=\"row flex-xl-nowrap \"> <form class=\"align-items-center input-command d-flex\">\n"
				"      <span class=\"display: inline-block d-inline-flex\">\n"
				"        <input type=\"text\" class=\"form_control\" placeholder=\">\" />\n"
				"      </span>\n"
				"    </form> -->\n"
				"\n"
				"  <!-- Menu and Navbar section -->\n"
				"  <nav id=\"navBar\" class=\"navbar navbar-expand-lg navbar-light bg-light\">\n"
				"    <a class=\"navbar-brand\" href=\"#\">ICON</a>\n"
				"    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				"      <span class=\"navbar-toggler-icon\"></span>\n"
				"    </button>\n"
				"\n"
				"    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
				"      <ul class=\"navbar-nav mr-auto\">\n"
				"        <li class=\"nav-item active\">\n"
				"          <a class=\"nav-link\" href=\"#\">Function 1</a>\n"
				"        </li>\n"
				"        <li class=\"nav-item active\">\n"
				"          <a class=\"nav-link\" href=\"#\">Function 2</a>\n"
				"        </li>\n"
				"        <li class=\"nav-item active\">\n"
				"          <a class=\"nav-link\" href=\"#\">Function 3</a>\n"
				"        </li>\n"
				"      </ul>\n"
				"      <form class=\"form-inline my-2 my-lg-0\">\n"
				"        <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n"
				"        <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n"
				"      </form>\n"
				"    </div>\n"
				"  </nav>\n"
				"\n"
				"  <!-- Map Display section -->\n"
				"  <div id=\"map_display\" class=\"map-display col-12 col-md-9 border border-primary\">\n"
				"    <span>\n"
				"      MAP\n"
				"    </span>\n"
				"    <!--<canvas class=\"drawing-panel\"></canvas>-->\n"
				"    <div class=\"drawing-panel\">\n"
				"      <img src=\"/content/526622.jpg\" id=\"4k_Pic\">\n"
				"    </div>\n"
				"\n"
				"  </div>\n"
				"\n"
				"  <!-- Controller section -->\n"
				"  <div class=\"side-bar\">\n"
				"    <div class=\"row justify-content-around ml-2 mr-2 mt-2 mb-2 \">\n"
				"      <div class=\"dropdown\">\n"
				"        <label for=\"starting\" class=\"col-form-label\">From: </label>\n"
				"        <button class=\"btn btn-sm btn-primary dropdown-toggle \" id=\"starting\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n"
				"          Start\n"
				"          <span class=\"caret\"></span>\n"
				"        </button>\n"
				"        <ul class=\"dropdown-menu\" id=\"menu\" aria-labelledby=\"dropdownMenu1\">\n"
				"          <li><a href=\"#\" class=\"dropdown-item\" value=\"1\">1</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\" value=\"2\">2</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\" value=\"3\">3</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\" value=\"4\">4</a></li>\n"
				"        </ul>\n"
				"      </div>\n"
				"      <div class=\"dropdown\">\n"
				"        <label for=\"stopping\" class=\"col-form-label\">To: </label>\n"
				"        <button id=\"stopping\" class=\"btn btn-sm btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n"
				"          End\n"
				"          <span class=\"caret\"></span>\n"
				"        </button>\n"
				"        <ul class=\"dropdown-menu\" id=\"menu2\" aria-labelledby=\"dropdownMenu1\">\n"
				"          <li><a href=\"#\" class=\"dropdown-item\">1</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\">2</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\">3</a></li>\n"
				"          <li><a href=\"#\" class=\"dropdown-item\">4</a></li>\n"
				"        </ul>\n"
				"      </div>\n"
				"      <button class=\"btn btn-sm btn-secondary \" id=\"OK\">\n"
				"        OK\n"
				"      </button>\n"
				"    </div>\n"
				"\n"
				"    <div class=\"col-12  d-xl-block border border-danger pt-3 pb-3 AGV_Section\">\n"
				"      <div class=\"control_panel\">\n"
				"        <div class=\"row \">\n"
				"          <span class=\"col-4\"> AGV #1 </span>\n"
				"          <div class=\"d-none d-md-block\"></div>\n"
				"          <div class=\"position col-4\" id=\"car_1_x\">\n"
				"            X:\n"
				"          </div>\n"
				"          <div class=\"position col-4\" id=\"car_1_y\">\n"
				"            Y:\n"
				"          </div>\n"
				"        </div>\n"
				"\n"
				"      </div>\n"
				"    </div>\n"
				"    <div class=\"row justify-content-end ml-3 mr-3 mt-2 mb-2\">\n"
				"      <button class=\"btn btn-sm btn-secondary mr-1\" id=\"Clear\">\n"
				"        Clear\n"
				"      </button>\n"
				"      <button class=\"btn btn-sm btn-secondary\" id=\"car_generate\">\n"
				"        AGV\n"
				"      </button>\n"
				"    </div>\n"
				"  </div>\n"
				"\n"
				"</body>\n"
				"\n"
				"<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"
				"<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js\" type=\"text/javascript\"></script>\n"
				"<!--<script type=\"text/javascript\" src=\"web_MVP_prop.js\"></script>-->\n"
				"<script type=\"text/javascript\" src=\"/content/style/web_image.js\"></script>\n"
				"<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\" integrity=\"sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut\" crossorigin=\"anonymous\"></script>\n"
				"<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n"
				"\n"
				"</html>\n"
				"\n"
				"";
		#line 134 "web_schema.tmpl"
		} // end of template render
	#line 135 "web_schema.tmpl"
	private:
	#line 135 "web_schema.tmpl"
		int _domain_id;
	#line 135 "web_schema.tmpl"
	}; // end of class message
#line 136 "web_schema.tmpl"
} // end of namespace my_skin
#line 2 "web_schema.tmpl"
namespace my_skin {
#line 136 "web_schema.tmpl"
} // end of namespace my_skin
#line 137 "web_schema.tmpl"
namespace {
#line 137 "web_schema.tmpl"
 cppcms::views::generator my_generator; 
#line 137 "web_schema.tmpl"
 struct loader { 
#line 137 "web_schema.tmpl"
  loader() { 
#line 137 "web_schema.tmpl"
   my_generator.name("my_skin");
#line 137 "web_schema.tmpl"
   my_generator.add_view<my_skin::message,content::message>("message",true);
#line 137 "web_schema.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 137 "web_schema.tmpl"
 }
#line 137 "web_schema.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 137 "web_schema.tmpl"
} a_loader;
#line 137 "web_schema.tmpl"
} // anon 
